name: TeamSpeakIP
author: tobias the best
version: 1.4
website: http://dev.bukkit.org/bukkit-plugins/teamspeak-ip/

main: me.Tobias.ts.Ts
database: false
commands:
  ts:
    description: /Ts
  tsupdate:
    description: /tsupdate